name: Clef
options:
  bundleIdPrefix: com.doldam0
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.4"
  defaultConfig: Debug
  groupSortPosition: top
  generateEmptyDirectories: true
  developmentLanguage: en
  knownRegions: [en, ko]

settings:
  base:
    SWIFT_VERSION: "6.0"
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  Clef:
    type: application
    platform: iOS
    sources:
      - path: Clef/Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.doldam0.Clef
        INFOPLIST_KEY_CFBundleDisplayName: Clef
        PRODUCT_NAME: Clef
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: true
        DEVELOPMENT_TEAM: 6882C9XWTW
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "2"  # iPad only
    info:
      path: Clef/Sources/Info.plist
      properties:
        CFBundleDocumentTypes:
          - CFBundleTypeName: PDF Document
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - com.adobe.pdf
        UISupportsDocumentBrowser: true
        LSSupportsOpeningDocumentsInPlace: true
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
