//  ClefWidgetControl.swift
//
//  Intentionally empty. Clef ships home-screen widgets (RecentScoresWidget and
//  FolderWidget) only; the Control Center template generated by Xcode was
//  removed from the widget bundle.
